name: Secure MQTT Publish from Docker

on:
  workflow_dispatch:

jobs:
  mqtt-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . -t mqtt-publisher

      - name: Run MQTT publish
        run: |
          docker run --rm \
            -e IOT_ENDPOINT="${{ secrets.IOT_ENDPOINT }}" \
            -e IOT_CERT="${{ secrets.IOT_CERT }}" \
            -e IOT_KEY="${{ secrets.IOT_KEY }}" \
            -e IOT_CA="${{ secrets.IOT_CA }}" \
            mqtt-publisher \
            sh -c '
              echo "$IOT_CA" > /tmp/ca.pem && \
              echo "$IOT_CERT" > /tmp/cert.pem && \
              echo "$IOT_KEY" > /tmp/key.pem && \
              chmod 644 /tmp/ca.pem && \
              chmod 644 /tmp/cert.pem && \
              chmod 600 /tmp/key.pem && \
              mosquitto_pub \
                -h "$IOT_ENDPOINT" \
                -p 8883 \
                -t "test/topic" \
                -m '\''{"data": "from GitHub CI securely"}'\'' \
                --cafile /tmp/ca.pem \
                --cert /tmp/cert.pem \
                --key /tmp/key.pem
            '
